spring:
  application:
    name: space-core


  datasource:
    url: jdbc:postgresql://localhost:5432/spacecore_db
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

    liquibase:
      enabled: true
      change-log: classpath:db/changelog/db.changelog-master.yaml
      default-schema: public
      drop-first: false

telegram:
  bot:
    token: ${BOT_TOKEN}

server:
  port: 8080

logging:
  level:
    org.example.spacecore: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    liquibase: INFO
